fastlane_version "1.70.0"

default_platform :ios

platform :ios do
  before_all do

  end

  desc "Runs all the tests"
  lane :push do
  	scan(
	  project: "DangerPoc.xcodeproj",
	  scheme: "DangerPoc",
	  clean: true,
	  code_coverage: true,
	  skip_build: true
	)

	xcov(
	  workspace: "DangerPoc.xcworkspace",
	  scheme: "DangerPoc"
	)

  danger
  end
end
